[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = true

[programs.devnet]
pumpfun = "Cu3ZCXsVh7xC64gWH23vjDeytWC6ZGcMRVYZAka92QTq"

[programs.localnet]
pumpfun = "Cu3ZCXsVh7xC64gWH23vjDeytWC6ZGcMRVYZAka92QTq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "../key/uu.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "spl-programs/metadata.so"
